name: eshop
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: 
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  location:
  provider:
  google_maps_flutter:
  permission_handler:

  awesome_card: ^1.1.7
  getwidget: ^1.2.4
  font_awesome_flutter: ^10.1.0
  
  im_stepper: 
  # percent_indicator: 


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - map_style.json
