name: eshop
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: 
  badges: ^2.0.3
  flutter_rating_bar: ^4.0.1
  geocoding: ^2.0.4
  photo_view: ^0.14.0
  video_player: ^2.2.17
  youtube_player_flutter: ^8.0.0
  http: ^0.13.4
  dart_json_mapper: ^2.1.17
  equatable: ^2.0.3
  uuid: ^3.0.6
  reflectable:
  build_runner: ^2.2.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  formz: ^0.4.1
  eva_icons_flutter: ^3.1.0
  top_snackbar_flutter: ^2.1.1
  html: ^0.15.0
  intl: ^0.17.0
  loading_animation_widget:
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  jwt_decoder: ^2.0.1
  
  # flutter_logs: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  location:
  provider:
  google_maps_flutter:
  permission_handler:

  webview_flutter: ^3.0.4
  awesome_card: ^1.1.7
  getwidget: ^1.2.4
  font_awesome_flutter: ^10.1.0
  
  im_stepper: 
  # percent_indicator: 


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - map_style.json
