// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.9

import 'dart:core';
import 'main.dart' as prefix2;
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:eshop/src/models/http_msg_model.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'HttpMsg',
            r'.HttpMsg',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 6, 7],
            const <int>[8, 9, 10, 11, 12, 13, 2, 3, 4, 5, 6],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({msg, code}) =>
                  b ? prefix1.HttpMsg(code: code, msg: msg) : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'msg', 32773, 0, const prefix0.JsonSerializable(),
            -1, 1, 1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'code',
            32773,
            0,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 2),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 3),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 4),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 5),
        r.MethodMirrorImpl(
            r'props',
            4325379,
            0,
            -1,
            4,
            5,
            const <int>[3],
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'==',
            131074,
            -1,
            -1,
            6,
            6,
            const <int>[],
            const <int>[4],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'toString',
            131074,
            -1,
            -1,
            7,
            7,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[5],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(
            r'hashCode',
            131075,
            -1,
            -1,
            8,
            8,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, 9, 9, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'stringify', 131075, -1, -1, 10, 10, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'msg',
            46086,
            7,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            #msg),
        r.ParameterMirrorImpl(
            r'code',
            46086,
            7,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            #code),
        r.ParameterMirrorImpl(
            r'_msg',
            32870,
            3,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_code',
            32870,
            5,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            8,
            const prefix0.JsonSerializable(),
            -1,
            11,
            11,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            10,
            const prefix0.JsonSerializable(),
            -1,
            12,
            12,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.HttpMsg,
        String,
        int,
        Object,
        const m.TypeValue<List<Object>>().type,
        List,
        bool,
        String,
        int,
        Type,
        bool,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'stringify': (dynamic instance) => instance.stringify,
        r'msg': (dynamic instance) => instance.msg,
        r'code': (dynamic instance) => instance.code,
        r'props': (dynamic instance) => instance.props
      },
      {
        r'msg=': (dynamic instance, value) => instance.msg = value,
        r'code=': (dynamic instance, value) => instance.code = value
      },
      null,
      []),
  const prefix2.MyReflectable(): r.ReflectorData(
      <m.TypeMirror>[], null, null, <Type>[], 0, {}, {}, null, [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
